name: Deploy
run-name: ${{github.actor}}

on: [push]
jobs:
    Deploy:
        runs-on: self-hosted
        steps:
            - run: git clone https://github.com/h12z/h12z.github.io.git:h12z -c /var/www/
            
